fix: #23 auro-pane selected attribute
AlaskaAirlines/auro-pane pull request #24
Opened 2022-06-22 17:57 UTC by ftaylor-alaska

Fixes #23

2022-06-23 16:41 UTC, jason-capsule42 requested changes
The build linter rules will fail if the object keys are not on separate lines.

2022-06-23 16:41 UTC, jason-capsule42 commented on src/auro-pane.js
> +      disabled: { type: Boolean, reflect: true },
```suggestion
      disabled: {
        type: Boolean,
        reflect: true
      },
```

2022-06-23 16:41 UTC, jason-capsule42 commented on src/auro-pane.js
> +      selected: { type: Boolean, reflect: true },
```suggestion
      disabled: {
        type: Boolean,
        reflect: true
      },
```

2022-06-29 17:47 UTC, blackfalcon commented
@ftaylor-alaska, per the comment from @geoffrich  this is a `feature` not a `bug`. Please update the commit message. Please review the Contributing guidelines https://auro.alaskaair.com/contributing

Please update the commit message to speak to the scope and the update, e.g. 

```
feat(selected attr): update to reflect true #23
```

An additional note, it is helpful to allow for feedback on the issue itself prior to creating and submitting the PR. This allows the Auro team to provide any feedback necessary prior to work being done and help the PR be released as soon as possible. We appreciate the support.

2022-06-29 17:49 UTC, blackfalcon commented
Question: is there a process you are using outside of Github? We are curious as to why pre-commit hooks are not catching issues also, how did you create this PR? Why was all the template content deleted?

2022-07-21 16:07 UTC, closed without merging