feat: add fixed property
AlaskaAirlines/auro-pane pull request #3
Opened 2020-10-05 23:09 UTC by gusnaughton

# Alaska Airlines Pull Request

For placements with weird body font-size values, use px values since our design system is 

## Type of change:

Please delete options that are not relevant.

- [x] New capability

## Checklist:

- [x] My update follows the CONTRIBUTING guidelines of this project
- [x] I have performed a self-review of my own update

**By submitting this Pull Request, I confirm that my contribution is made under the terms of the Apache 2.0 license.**

_Pull Requests will be evaluated by their quality of update and whether it is consistent with the goals and values of this project. Any submission is to be considered a conversation between the submitter and the maintainers of this project and may require changes to your submission._

**Thank you for your submission!**<br>
-- Auro Design System Team

2020-10-06 15:05 UTC, geoffrich requested changes

2020-10-06 15:05 UTC, geoffrich commented on src/style.scss
> +      font-size: 18px;
Should be 20px

2020-10-06 15:05 UTC, geoffrich commented on src/style.scss
> +      font-size: 16px;
Should be 18px

2020-10-06 15:05 UTC, geoffrich commented on src/style.scss
> +:host([fixed]) {
There's a bunch of other properties set to rems as well (e.g. height, width, row size, padding). If we want the pane to display correctly we need to set those as well.

2020-10-06 16:19 UTC, geoffrich commented on src/style.scss
> +      font-size: 16px;
No longer needed since fixed styles are automatically generated.

2020-10-06 16:19 UTC, geoffrich commented on src/style.scss
> +:host([fixed]) {
Fixed styles are now automatically generated.

2020-10-06 16:41 UTC, geoffrich approved these changes

2020-10-06 16:42 UTC, merged

2020-10-06 16:53 UTC, ecommerceUXdesign commented
:tada: This PR is included in version 1.1.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@alaskaairux/auro-pane/v/1.1.0)
- [GitHub release](https://github.com/AlaskaAirlines/auro-pane/releases/tag/v1.1.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2020-10-07 20:26 UTC, blackfalcon commented
I really like this solution, but I am wondering if this needs to be more dynamic. The additional CSS is large and in-light of the conversations I am having with @geoffrich about bundle size, I am wondering if this should actually be a functional attribute that decides which CSS to load? 

I do see that the fixed-value CSS is smaller than the standard, so this is only addressing non-REM value CSS. But if we remove that plug-in then we could have a full stylesheet that is all the CSS with px values. 

The good news is that the API doesn't change. The return is simply refactored.

2020-10-08 15:52 UTC, geoffrich commented
I'd be in favor of finding a way to conditionally load this. Not entirely sure what that would look like though. We could subclass it like we do for light-dom (auro-pane-fixed?) but I'm not in love with that, especially since it would get messy if applied to other components with a light version (auro-button-light, auro-button-fixed, auro-button-light-fixed...)

Would dynamic imports be something we could use here?

2020-10-08 22:20 UTC, blackfalcon commented
I don't have all the details thought out ... I am pondering ideas and will come back to this.