Refactor color tokens for theming capabilities
AlaskaAirlines/auro-pane pull request #63
Opened 2024-06-04 19:55 UTC by jordanjones243

# Alaska Airlines Pull Request

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

**Resolves:** #59 

## Summary:

_Please summarize the scope of the changes you have submitted, what the intent of the work is and anything that describes the before/after state of the project._

* Update dependencies
* Refactor color tokens by isolating the color tokens and creating tier 3 tokens for repeatable rules
* Replace hardcoded size values with tokens

## Type of change:

Please delete options that are not relevant.

- [x] New capability
- [x] Revision of an existing capability
- [ ] Infrastructure change (automation, etc.)
- [ ] Other (please elaborate)

## Checklist:

- [x] My update follows the CONTRIBUTING guidelines of this project
- [x] I have performed a self-review of my own update

## Verification
- [ ] Color UI is correct in all states (active, focus, hover)
- [ ] Layout of component looks correct
- [ ] Tier 3 tokens have acceptable names
- [ ] All correct tier 2 tokens are being used

**By submitting this Pull Request, I confirm that my contribution is made under the terms of the Apache 2.0 license.**

_Pull Requests will be evaluated by their quality of update and whether it is consistent with the goals and values of this project. Any submission is to be considered a conversation between the submitter and the maintainers of this project and may require changes to your submission._

**Thank you for your submission!**<br>
-- Auro Design System Team

2024-07-01 16:23 UTC, jason-capsule42 requested changes

2024-07-01 16:23 UTC, jason-capsule42 commented on demo/api.md
> +  --ds-auro-pane-background-color: var(--ds-color-container-secondary-default, $ds-color-container-secondary-default);
```suggestion
  --ds-auro-pane-container-color: var(--ds-color-container-secondary-default, $ds-color-container-secondary-default);
```

2024-07-01 16:23 UTC, jason-capsule42 commented on src/color.scss
> +        --ds-auro-pane-background-color: var(--ds-color-container-ui-primary-hover-default, #{$ds-color-container-ui-primary-hover-default});
```suggestion
        --ds-auro-pane-container-color: var(--ds-color-container-ui-primary-hover-default, #{$ds-color-container-ui-primary-hover-default});
```

2024-07-01 21:11 UTC, jordanjones243 commented on src/tokens.scss
> +  --ds-auro-pane-price-empty-text-color: var(--ds-color-text-secondary-default, $ds-color-text-secondary-default);
Tokens are alphabetized and we only need to add `#{...}` to the `color.scss` file

2024-07-09 02:00 UTC, jason-capsule42 approved these changes

2024-07-09 02:00 UTC, merged